# -*- coding: utf-8 -*-
"""suc_ternary-quant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9m_kq5PRVk_aR2pwsxo0vd8zK2C7cUP
"""







"""https://github.com/Asad-Ismail/ternary-models

https://huggingface.co/AsadIsmail/Qwen3-1.7B-ternary

https://github.com/vinsis/ternary-quantization

https://www.google.com/search?q=ternary-quant&oq=ternary-quant&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQABgeMgYIAhBFGDwyBggDEEUYQTIGCAQQRRg8MgYIBRBFGDwyBggGEEUYQTIGCAcQRRhB0gEJMTE4NzFqMGo3qAIIsAIB8QXw69VSc9DUFA&sourceid=chrome&source=chrome.ob&ie=UTF-8

https://github.com/topics/ternary-quantization
"""

!pip install ternary-quant

ternary-quant

from ternary_quant.inference import load_ternary_model
# CPU — auto BF16 on Intel AVX2+
model, tokenizer = load_ternary_model(
    "AsadIsmail/Qwen3-1.7B-ternary", device="cpu", runtime_mode="cached"
)
# Generate
from ternary_quant.inference import generate_text
output = generate_text(model, tokenizer, "Ternary quantization works by", max_new_tokens=100)
print(output)

# Generate
from ternary_quant.inference import generate_text
output = generate_text(model, tokenizer, "Napoleon Bonaparte is", max_new_tokens=100)
print(output)







from ternary_quant.inference import load_ternary_model
# CPU — auto BF16 on Intel AVX2+
model, tokenizer = load_ternary_model(
    "AsadIsmail/Qwen3-1.7B-ternary", device="cpu", runtime_mode="cached"
)
# Generate
from ternary_quant.inference import generate_text
output = generate_text(model, tokenizer, "Ternary quantization works by", max_new_tokens=100)
print(output)

from ternary_quant.inference import load_ternary_model

# GPU — fastest (dequantize once, use cuBLAS)
model, tokenizer = load_ternary_model(
    "AsadIsmail/Qwen3-1.7B-ternary", device="cuda", runtime_mode="cached"
)

# GPU — lowest VRAM (~1.0 GB (use runtime_mode='gemlite' or 'triton'))
model, tokenizer = load_ternary_model(
    "AsadIsmail/Qwen3-1.7B-ternary", device="cuda", runtime_mode="gemlite"
)

# CPU — auto BF16 on Intel AVX2+
model, tokenizer = load_ternary_model(
    "AsadIsmail/Qwen3-1.7B-ternary", device="cpu", runtime_mode="cached"
)

# Apple Silicon
model, tokenizer = load_ternary_model(
    "AsadIsmail/Qwen3-1.7B-ternary", device="mps", runtime_mode="metal"
)

# Generate
from ternary_quant.inference import generate_text
output = generate_text(model, tokenizer, "Ternary quantization works by", max_new_tokens=100)
print(output)